sudo: required
dist: trusty
language: node_js
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - stable
install:
  - npm i

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm prune
script:
  - export CHROME_BIN=chromium-browser
  - xvfb-run -a npm run test
  - xvfb-run -a npm run build
after_success:
  - npm run publish
